### ISSUE TITLE
Figure out which option to go with regarding images in IupEmscripten

### ISSUE THREAD

**Issue by cmatzenbach** [ewmailing/IupEmscripten#33]
Options:
1. Use SDL Built-in Image Support or SDL Image Support Provided by Emscripten
2. FInd JS API that can load images natively and continue same way we've been doing
3. Compile in our own image library from the c-side
4. Write our own image loader (NOT!!)

#1 Eric's preferred option

**Comment by cmatzenbach** [comment]
@ewmailing Did you learn anything about this, or have thought about it further since I opened the ticket?

**Comment by ewmailing** [comment]
I did an implementation and is committed. It uses SDL_image to load, and then does a lot of ugly things to get it into a DOM widget. It has its own issues which should be filed, but this can be closed.
