### ISSUE TITLE
IupLabel->IMINACTIVE

### ISSUE THREAD

**Issue by cmatzenbach** [ewmailing/IupEmscripten#7]

**Comment by cmatzenbach** [comment]
@ewmailing What is this widget?  Can you provide details?  Does it just render an image when the element is set as inactive?

**Comment by ewmailing** [comment]
Docs say GTK and Motif only

**Comment by cmatzenbach** [comment]
@ewmailing ok so when we see that we can skip (even if we could implement such a feature)?  Wondering as this comes up semi-frequently @zNeill

**Comment by ewmailing** [comment]
If you think it is a common or useful feature, then consider implementing it. But I don't really know what this thing is, and consider Motif is an ancient primitive toolkit which almost nobody uses today.

To me, it sounds like this thing might change an image to some placeholder text when the widget is not in-focus. If this is true, it sounds like some memory saving technique when it was too hardware expensive to show unneeded images on the screen. I don't think anybody really needs that today.

**Comment by cmatzenbach** [comment]
Ok great, makes sense.  Thanks.  Closing now
