### ISSUE TITLE
IupLabel->MARKUP

### ISSUE THREAD

**Issue by cmatzenbach** [ewmailing/IupEmscripten#8]

**Comment by cmatzenbach** [comment]
@ewmailing How should we create this widget?  Do we need to create some sort of markdown renderer in javascript, or will this be handled by Iup?

**Comment by ewmailing** [comment]
The docs say it is GTK only and for Pango Markup. This is probably not the same as Markdown.

**Comment by cmatzenbach** [comment]
@ewmailing ok thanks.  will close on account of gtk only
